### ISSUE TITLE
Unbalanced quotes errors

### ISSUE THREAD

**Issue by monkoose** [harrygallagher4/nvim-parinfer-rust#7]
First of all, thank you for this plugin. It feel really smooth compare to other alternatives.

Should quotes to be autobalanced too? Because currently it doesn't for me with a lot of errors from the plugin.
```
Error detected while processing TextChangedI Autocommands for "<buffer=13>":
[Parinfer] error in buffer 13
{"name":"unclosed-quote","message":"String is missing a closing quote.","inputLineNo":11,"inputX":7,"lineNo":8,"x":23}
{"options":{"guileBlockComments":false,"schemeSexpComments":false,"janetLongStrings":false,"cursorLine":2,"prevText":"(local utils (require \"custom.ut
ils\"))\n\n\n(fn open []\n  \"Opens link under the cursor\"\n  (let [link (vim.fn.expand \"<cfile>\")]\n    (vim.fn.jobstart [\"xdg-open\" link])\n
(nvim.command \"redraw\")\n    (utils.echo [\"Open \" :String]\n                [link :Identifier])))\n\n{: open}","cursorX":1,"prevCursorX":0,"prevCur
sorLine":2,"commentChar":";","stringDelimiters":["\""],"forceBalance":false,"lispVlineSymbols":false,"lispBlockComments":false},"text":"(local utils (r
equire \"custom.utils\"))\n\n\"\n(fn open []\n  \"Opens link under the cursor\"\n  (let [link (vim.fn.expand \"<cfile>\")]\n    (vim.fn.jobstart [\"xdg
-open\" link])\n    (nvim.command \"redraw\")\n    (utils.echo [\"Open \" :String]\n                [link :Identifier])))\n\n{: open}","mode":"smart"}
```
and some others like
```
Error detected while processing TextChangedI Autocommands for "<buffer=3>":
[Parinfer] error in buffer 3
{"name":"quote-danger","x":31,"message":"Quotes must balanced inside comment blocks.","inputX":16,"inputLineNo":152,"lineNo":151}
... there is some stacktrace
```

**Comment by harrygallagher4** [comment]
Whoops, sorry about the error notifications lol. Since I wrote this for personal use I was willing to put up with a ton of debugging info whenever something went wrong. I'll push an update to disable the notifications for now, I intend to report errors via diagnostics/virtual text in the future but haven't found time to implement that yet.

As for balancing quotes, parinfer-rust does not handle that. I would recommend configuring an auto-pair plugin to do *quotes only* when in a filetype that uses parinfer. I use delimitMate but I'm sure any auto-pair plugin be configured that way.

**Comment by monkoose** [comment]
Thank you. Will wait for update.

**Comment by harrygallagher4** [comment]
Notifications are disabled as of the latest update!

**Comment by monkoose** [comment]
Let me try. I will close it afterwards. Thank you.

**Comment by monkoose** [comment]
Seems like no errors for now. Closed.
